"""Offline Graph fixtures with actual DLT extraction and SQLite replacement."""

from collections import Counter
from copy import deepcopy

import dlt
import httpx
import pytest
from dlt.pipeline.exceptions import PipelineStepFailed

from cognee_community_connector_onenote import list_notebooks, onenote_source
from cognee_community_connector_onenote.onenote import OneNoteError


class Graph:
    def __init__(self):
        self.notebooks = {"a": "Project Alpha", "b": "Excluded"}
        self.sections = {"a": "Planning", "b": "Private"}
        self.pages = {"a": [self.page("p1")], "b": [self.page("secret")]}
        self.html = {
            "p1": "<html><body><h1>Plan</h1><p>Original body</p>"
            '<img alt="Architecture diagram" src="https://graph.microsoft.com/v1.0/'
            'me/onenote/resources/image/content"></body></html>',
            "secret": "<p>Excluded content</p>",
        }
        self.errors = {}
        self.requests = []
        self.gone_code = "20113"

    @staticmethod
    def page(identity, timestamp="2026-10-01T00:00:00Z"):
        return {
            "id": identity,
            "title": identity,
            "lastModifiedDateTime": timestamp,
            "links": {"oneNoteWebUrl": {"href": f"https://onenote.com/{identity}"}},
        }

    def handle(self, request):
        assert request.headers["Authorization"] == "Bearer offline-token"
        path = request.url.path.removeprefix("/v1.0/me/onenote/")
        self.requests.append((path, dict(request.url.params)))
        if path in self.errors:
            status, code = self.errors[path]
            return httpx.Response(
                status, json={"error": {"code": code, "message": "Fixture error"}}
            )
        parts = path.split("/")
        if path == "notebooks":
            values = [
                {"id": identity, "displayName": title} for identity, title in self.notebooks.items()
            ]
        elif parts[0] == "notebooks" and len(parts) == 2:
            return httpx.Response(
                200, json={"id": parts[1], "displayName": self.notebooks[parts[1]]}
            )
        elif parts[0] == "notebooks" and parts[-1] == "sections":
            values = [{"id": f"s-{parts[1]}", "displayName": self.sections[parts[1]]}]
        elif parts[-1] == "sectionGroups":
            values = []
        elif parts[0] == "sections" and parts[-1] == "pages":
            values = self.pages[parts[1].removeprefix("s-")]
        elif parts[0] == "pages" and parts[-1] == "content":
            return httpx.Response(
                200,
                text=f"<html><body>{self.html[parts[1]]}</body></html>",
                headers={"content-type": "text/html"},
            )
        elif parts[0] == "pages":
            for notebook, pages in self.pages.items():
                for page in pages:
                    if page["id"] == parts[1]:
                        metadata = deepcopy(page)
                        metadata["parentNotebook"] = {
                            "id": notebook,
                            "displayName": self.notebooks[notebook],
                        }
                        metadata["parentSection"] = {
                            "id": f"s-{notebook}",
                            "displayName": self.sections[notebook],
                        }
                        return httpx.Response(200, json=metadata)
            return httpx.Response(
                404, json={"error": {"code": self.gone_code, "message": "Page gone"}}
            )
        else:
            raise AssertionError(f"Unexpected Graph request: {request.url}")
        skip = int(request.url.params.get("$skip", "0"))
        top = int(request.url.params.get("$top", "100"))
        return httpx.Response(200, json={"value": values[skip : skip + top]})

    def client(self):
        return httpx.Client(transport=httpx.MockTransport(self.handle))

    def content_requests(self):
        return Counter(path for path, _ in self.requests if path.endswith("/content"))


@pytest.fixture
def pipeline(tmp_path):
    return dlt.pipeline(
        pipeline_name="onenote_test",
        destination=dlt.destinations.sqlalchemy(f"sqlite:///{tmp_path}/data.db"),
        dataset_name="notes",
        pipelines_dir=str(tmp_path / "state"),
    )


def sync(pipeline, graph, selection=("a",), account="tenant:user", **kwargs):
    with graph.client() as client:
        source = onenote_source(
            "offline-token",
            notebook_ids=list(selection),
            account_id=account,
            http_client=client,
            **kwargs,
        )
        tables = list(source.resources.keys())
        pipeline.run(source)
    return tables


def rows(pipeline, table):
    # Table names are generated by the connector, never supplied by a provider.
    assert table.replace("_", "").isalnum()
    with pipeline.sql_client() as client:
        with client.execute_query(f'SELECT id, title, content FROM "{table}"') as cursor:
            return list(cursor.fetchall())


def test_initial_selection_html_and_unchanged_replay(pipeline):
    graph = Graph()
    (table,) = sync(pipeline, graph)
    first = rows(pipeline, table)
    assert len(first) == 1
    assert "Original body" in first[0][2]
    assert "Project Alpha" in first[0][2]
    assert "Planning" in first[0][2]
    assert "Architecture diagram" in first[0][2]
    assert "resources/image/content" in first[0][2]
    calls = graph.content_requests()
    sync(pipeline, graph)
    assert rows(pipeline, table) == first
    assert graph.content_requests() == calls
    assert not any("secret" in path for path, _ in graph.requests)


def test_rename_rebuilds_breadcrumbs_without_html_fetch(pipeline):
    graph = Graph()
    (table,) = sync(pipeline, graph)
    calls = graph.content_requests()
    graph.notebooks["a"] = "Project Beta"
    graph.sections["a"] = "Execution"
    sync(pipeline, graph)
    content = rows(pipeline, table)[0][2]
    assert "Project Beta" in content and "Execution" in content
    assert "Project Alpha" not in content and "Planning" not in content
    assert graph.content_requests() == calls


def test_edits_timestamp_only_and_older_new_page(pipeline):
    graph = Graph()
    (table,) = sync(pipeline, graph)
    first = rows(pipeline, table)
    graph.pages["a"][0]["lastModifiedDateTime"] = "2026-10-02T00:00:00Z"
    sync(pipeline, graph)
    assert rows(pipeline, table) == first
    graph.pages["a"][0]["lastModifiedDateTime"] = "2026-10-03T00:00:00Z"
    graph.html["p1"] = "<p>Updated body</p>"
    graph.pages["a"].append(Graph.page("older", "2020-01-01T00:00:00Z"))
    graph.html["older"] = "<p>Older new page</p>"
    sync(pipeline, graph)
    content = "\n".join(row[2] for row in rows(pipeline, table))
    assert "Updated body" in content and "Older new page" in content
    assert "Original body" not in content


@pytest.mark.parametrize("code", ["20113", "20102"])
def test_confirmed_final_page_deletion_physically_empties_table(pipeline, code):
    graph = Graph()
    (table,) = sync(pipeline, graph)
    graph.pages["a"] = []
    graph.gone_code = code
    sync(pipeline, graph)
    assert rows(pipeline, table) == []


@pytest.mark.parametrize(
    "status,code",
    [(403, "40003"), (404, "20112"), (404, "unknown"), (401, "20113"), (403, "20102")],
)
def test_missing_page_access_or_ambiguous_failure_preserves_table(pipeline, status, code):
    graph = Graph()
    (table,) = sync(pipeline, graph)
    before = rows(pipeline, table)
    graph.pages["a"] = []
    graph.errors["pages/p1"] = (status, code)
    with pytest.raises(PipelineStepFailed):
        sync(pipeline, graph)
    assert rows(pipeline, table) == before


def test_failed_second_notebook_does_not_publish_partial_snapshot(pipeline):
    graph = Graph()
    tables = sync(pipeline, graph, ("a", "b"))
    before = {table: rows(pipeline, table) for table in tables}
    graph.pages["a"][0]["lastModifiedDateTime"] = "2026-10-03T00:00:00Z"
    graph.html["p1"] = "<p>Uncommitted update</p>"
    graph.errors["notebooks/b/sections"] = (403, "40003")
    with pytest.raises(PipelineStepFailed):
        sync(pipeline, graph, ("a", "b"))
    assert {table: rows(pipeline, table) for table in tables} == before
    del graph.errors["notebooks/b/sections"]
    sync(pipeline, graph, ("a", "b"))
    assert any("Uncommitted update" in row[2] for table in tables for row in rows(pipeline, table))


def test_deselection_preserves_table_and_reselection_cache(pipeline):
    graph = Graph()
    tables = sync(pipeline, graph, ("a", "b"))
    before = {table: rows(pipeline, table) for table in tables}
    calls = graph.content_requests()
    sync(pipeline, graph, ("a",))
    assert {table: rows(pipeline, table) for table in tables} == before
    sync(pipeline, graph, ("a", "b"))
    assert graph.content_requests() == calls


def test_account_scope_produces_separate_resources(pipeline):
    graph = Graph()
    first = sync(pipeline, graph, account="tenant:first")
    second = sync(pipeline, graph, account="tenant:second")
    assert set(first).isdisjoint(second)
    assert all(len(rows(pipeline, table)) == 1 for table in first + second)
    assert graph.content_requests()["pages/p1/content"] == 2


@pytest.mark.parametrize("count", [0, 3, 100, 200])
def test_exact_pagination_boundaries(pipeline, count):
    graph = Graph()
    graph.pages["a"] = [Graph.page(f"p{i}") for i in range(count)]
    graph.html.update({f"p{i}": f"<p>Body {i}</p>" for i in range(count)})
    (table,) = sync(pipeline, graph)
    assert len(rows(pipeline, table)) == count


def test_page_limit_failure_preserves_previous_snapshot(pipeline):
    graph = Graph()
    (table,) = sync(pipeline, graph)
    before = rows(pipeline, table)
    graph.pages["a"].append(Graph.page("p2"))
    graph.html["p2"] = "<p>Too many</p>"
    with pytest.raises(PipelineStepFailed):
        sync(pipeline, graph, max_pages=1)
    assert rows(pipeline, table) == before


def test_cache_size_failure_preserves_previous_snapshot(pipeline):
    graph = Graph()
    (table,) = sync(pipeline, graph)
    before = rows(pipeline, table)
    with pytest.raises(PipelineStepFailed):
        sync(pipeline, graph, max_cache_bytes=1)
    assert rows(pipeline, table) == before


def test_notebook_listing_uses_delegated_token_provider():
    graph = Graph()
    with graph.client() as client:
        result = list_notebooks(lambda: "offline-token", http_client=client)
    assert {item["id"] for item in result} == {"a", "b"}


def test_empty_selection_is_rejected():
    with pytest.raises(ValueError):
        onenote_source("offline-token", notebook_ids=[], account_id="account")


def test_confirmed_move_outside_selection_retains_copy_without_fetch(pipeline):
    graph = Graph()
    (table,) = sync(pipeline, graph)
    before = rows(pipeline, table)
    calls = graph.content_requests()
    graph.pages["b"].append(graph.pages["a"].pop())
    graph.html["p1"] = "<p>Excluded update</p>"
    sync(pipeline, graph)
    assert rows(pipeline, table) == before
    assert graph.content_requests() == calls


def test_move_between_selected_notebooks_reuses_body(pipeline):
    graph = Graph()
    tables = sync(pipeline, graph, ("a", "b"))
    calls = graph.content_requests()
    graph.pages["b"].append(graph.pages["a"].pop())
    sync(pipeline, graph, ("a", "b"))
    all_rows = [row for table in tables for row in rows(pipeline, table)]
    assert len(all_rows) == 2
    moved = next(row for row in all_rows if "Original body" in row[2])
    assert "Excluded > Private" in moved[2]
    assert graph.content_requests() == calls


def test_renderer_version_invalidates_unchanged_cache(pipeline, monkeypatch):
    from cognee_community_connector_onenote import onenote

    graph = Graph()
    sync(pipeline, graph)
    monkeypatch.setattr(onenote, "_RENDERER_VERSION", onenote._RENDERER_VERSION + 1)
    sync(pipeline, graph)
    assert graph.content_requests()["pages/p1/content"] == 2


def test_pending_load_recovery_then_fresh_extraction(pipeline, monkeypatch):
    graph = Graph()
    (table,) = sync(pipeline, graph)
    graph.pages["a"][0]["lastModifiedDateTime"] = "2026-10-03T00:00:00Z"
    graph.html["p1"] = "<p>Recover me</p>"
    original_load = pipeline.load

    def failed_load(*args, **kwargs):
        raise RuntimeError("Injected load failure")

    monkeypatch.setattr(pipeline, "load", failed_load)
    with pytest.raises(RuntimeError, match="Injected load failure"):
        sync(pipeline, graph)
    calls = graph.content_requests()
    monkeypatch.setattr(pipeline, "load", original_load)
    with graph.client() as client:
        source = onenote_source(
            "offline-token", notebook_ids=["a"], account_id="tenant:user", http_client=client
        )
        pipeline.run(source)
        assert source._onenote_extracted is False
    assert "Recover me" in rows(pipeline, table)[0][2]
    sync(pipeline, graph)
    assert graph.content_requests() == calls
    assert "Recover me" in rows(pipeline, table)[0][2]


def test_declared_document_and_dataset_scope():
    from cognee.tasks.ingestion.dlt_utils import (
        DOCUMENT_SOURCE_ATTR,
        PIPELINE_SCOPE_ATTR,
        pipeline_name_for_source,
    )

    source = onenote_source("offline-token", notebook_ids=["a"], account_id="tenant:user")
    assert getattr(source, DOCUMENT_SOURCE_ATTR).startswith("onenote_")
    assert getattr(source, PIPELINE_SCOPE_ATTR)
    assert pipeline_name_for_source(source, "first") != pipeline_name_for_source(source, "second")


@pytest.mark.parametrize("status", [429, 503])
def test_retry_after_and_five_total_attempts(monkeypatch, status):
    from cognee_community_connector_onenote import onenote

    sleeps = []
    monkeypatch.setattr(onenote.time, "sleep", sleeps.append)
    requests = []

    def throttled(request):
        requests.append(request)
        return httpx.Response(
            status, headers={"Retry-After": "2"}, json={"error": {"code": "throttled"}}
        )

    with httpx.Client(transport=httpx.MockTransport(throttled)) as client:
        with pytest.raises(OneNoteError):
            list_notebooks("offline-token", http_client=client)
    assert len(requests) == 5
    assert sleeps == [2] * 4


def test_retry_recovers_and_token_is_not_in_error(monkeypatch):
    from cognee_community_connector_onenote import onenote

    monkeypatch.setattr(onenote.time, "sleep", lambda _: None)
    requests = []

    def response(request):
        requests.append(request)
        if len(requests) == 1:
            return httpx.Response(429, headers={"Retry-After": "0"})
        return httpx.Response(200, json={"value": []})

    with httpx.Client(transport=httpx.MockTransport(response)) as client:
        assert list_notebooks("offline-token", http_client=client) == []
    assert len(requests) == 2
    with httpx.Client(transport=httpx.MockTransport(lambda _: httpx.Response(401))) as client:
        with pytest.raises(OneNoteError, match="reauthenticate") as failure:
            list_notebooks("secret-token", http_client=client)
    assert "secret-token" not in str(failure.value)


def test_transport_failure_has_bounded_backoff_and_redacted_diagnostics(monkeypatch):
    from cognee_community_connector_onenote import onenote

    requests, sleeps = [], []
    monkeypatch.setattr(onenote.time, "sleep", sleeps.append)

    def timeout(request):
        requests.append(request)
        raise httpx.ReadTimeout("secret-token", request=request)

    with httpx.Client(transport=httpx.MockTransport(timeout)) as client:
        with pytest.raises(OneNoteError) as failure:
            list_notebooks("secret-token", http_client=client)
    assert len(requests) == 5
    assert sleeps == [1, 2, 4, 8]
    assert "secret-token" not in str(failure.value)


@pytest.mark.parametrize("retry_after", ["bad", "-1", "inf", "nan"])
def test_invalid_retry_after_uses_bounded_fallback(monkeypatch, retry_after):
    from cognee_community_connector_onenote import onenote

    sleeps = []
    monkeypatch.setattr(onenote.time, "sleep", sleeps.append)
    with httpx.Client(
        transport=httpx.MockTransport(
            lambda _: httpx.Response(429, headers={"Retry-After": retry_after})
        )
    ) as client:
        with pytest.raises(OneNoteError):
            list_notebooks("offline-token", http_client=client)
    assert sleeps == [1, 2, 4, 8]


@pytest.mark.parametrize(
    "next_link",
    [
        "http://graph.microsoft.com/v1.0/me/onenote/notebooks",
        "https://evil.example/v1.0/me/onenote/notebooks",
        "https://graph.microsoft.com.evil.example/v1.0/me/onenote/notebooks",
        "https://user:password@graph.microsoft.com/v1.0/me/onenote/notebooks",
    ],
)
def test_unsafe_pagination_link_never_receives_token(next_link):
    requests = []

    def response(request):
        requests.append(request)
        return httpx.Response(200, json={"value": [{"id": "a"}], "@odata.nextLink": next_link})

    with httpx.Client(transport=httpx.MockTransport(response)) as client:
        with pytest.raises(OneNoteError, match="Unsafe"):
            list_notebooks("offline-token", http_client=client)
    assert len(requests) == 1


def test_injected_redirect_enabled_client_still_does_not_follow_redirects():
    requests = []

    def redirect(request):
        requests.append(request)
        return httpx.Response(302, headers={"Location": "https://evil.example"})

    with httpx.Client(transport=httpx.MockTransport(redirect), follow_redirects=True) as client:
        with pytest.raises(OneNoteError):
            list_notebooks("offline-token", http_client=client)
    assert len(requests) == 1


@pytest.mark.parametrize("duplicate", [False, True])
def test_next_link_cycle_and_duplicate_page_fail(duplicate):
    requests = []

    def response(request):
        requests.append(request)
        item_id = "a" if duplicate else str(len(requests))
        next_link = (
            "https://graph.microsoft.com/v1.0/me/onenote/notebooks?$skiptoken=next"
            if duplicate
            else str(request.url)
        )
        return httpx.Response(200, json={"value": [{"id": item_id}], "@odata.nextLink": next_link})

    with httpx.Client(transport=httpx.MockTransport(response)) as client:
        with pytest.raises(OneNoteError):
            list_notebooks("offline-token", http_client=client)
    assert len(requests) == (2 if duplicate else 1)


def test_successful_next_link_is_followed():
    requests = []

    def response(request):
        requests.append(request)
        if len(requests) == 1:
            return httpx.Response(
                200,
                json={
                    "value": [{"id": "a"}],
                    "@odata.nextLink": "https://graph.microsoft.com/v1.0/me/onenote/"
                    "notebooks?$skiptoken=next",
                },
            )
        assert request.url.params["$skiptoken"] == "next"
        return httpx.Response(200, json={"value": [{"id": "b"}]})

    with httpx.Client(transport=httpx.MockTransport(response)) as client:
        assert [row["id"] for row in list_notebooks("offline-token", http_client=client)] == [
            "a",
            "b",
        ]


def test_confirmed_parent_deletion_reconciles_descendant_and_empty_table(pipeline):
    graph = Graph()
    (table,) = sync(pipeline, graph)
    del graph.notebooks["a"]
    graph.pages["a"] = []
    graph.errors["notebooks/a"] = (404, "20113")
    sync(pipeline, graph)
    assert rows(pipeline, table) == []
    assert any(path == "pages/p1" for path, _ in graph.requests)


@pytest.mark.parametrize("status,code", [(403, "40003"), (404, "20102")])
def test_inaccessible_parent_is_not_treated_as_deletion(pipeline, status, code):
    graph = Graph()
    (table,) = sync(pipeline, graph)
    before = rows(pipeline, table)
    del graph.notebooks["a"]
    graph.errors["notebooks/a"] = (status, code)
    with pytest.raises(PipelineStepFailed):
        sync(pipeline, graph)
    assert rows(pipeline, table) == before


def test_malformed_collection_preserves_loaded_table(pipeline):
    graph = Graph()
    (table,) = sync(pipeline, graph)
    before = rows(pipeline, table)
    original = graph.handle

    def malformed(request):
        if request.url.path.endswith("/sections/s-a/pages"):
            return httpx.Response(200, json={"value": None})
        return original(request)

    graph.handle = malformed
    with pytest.raises(PipelineStepFailed):
        sync(pipeline, graph)
    assert rows(pipeline, table) == before


def test_later_pagination_failure_preserves_snapshot_and_cache(pipeline):
    graph = Graph()
    (table,) = sync(pipeline, graph)
    before = rows(pipeline, table)
    calls = graph.content_requests()
    original = graph.handle
    graph.pages["a"] = [Graph.page(f"p{i}") for i in range(101)]

    def failed_batch(request):
        if (
            request.url.path.endswith("/sections/s-a/pages")
            and request.url.params.get("$skip") == "100"
        ):
            return httpx.Response(403, json={"error": {"code": "40003"}})
        return original(request)

    graph.handle = failed_batch
    with pytest.raises(PipelineStepFailed):
        sync(pipeline, graph)
    assert rows(pipeline, table) == before
    assert graph.content_requests() == calls
    graph.handle = original
    graph.pages["a"] = [Graph.page("p1")]
    sync(pipeline, graph)
    assert rows(pipeline, table) == before
    assert graph.content_requests() == calls


@pytest.fixture
def nested_graph():
    graph = Graph()
    original = graph.handle

    def nested(request):
        path = request.url.path.removeprefix("/v1.0/me/onenote/")
        if path == "notebooks/a/sections":
            return httpx.Response(200, json={"value": []})
        if path == "notebooks/a/sectionGroups":
            return httpx.Response(200, json={"value": [{"id": "group", "displayName": "Research"}]})
        if path == "sectionGroups/group/sections" and path not in graph.errors:
            return httpx.Response(200, json={"value": [{"id": "s-a", "displayName": "Planning"}]})
        return original(request)

    graph.handle = nested
    return graph


def test_section_group_recursion_renders_complete_breadcrumb(pipeline, nested_graph):
    graph = nested_graph
    (table,) = sync(pipeline, graph)
    assert "Project Alpha > Research > Planning" in rows(pipeline, table)[0][2]


@pytest.mark.parametrize("container_path", ["sections/s-a/pages", "sectionGroups/group/sections"])
def test_confirmed_section_or_group_deletion_reconciles_pages(
    pipeline, nested_graph, container_path
):
    graph = nested_graph
    (table,) = sync(pipeline, graph)
    graph.pages["a"] = []
    graph.errors[container_path] = (404, "20113")
    sync(pipeline, graph)
    assert rows(pipeline, table) == []
    assert any(path == "pages/p1" for path, _ in graph.requests)


@pytest.mark.parametrize("container_path", ["sections/s-a/pages", "sectionGroups/group/sections"])
def test_section_or_group_access_loss_preserves_snapshot(pipeline, nested_graph, container_path):
    graph = nested_graph
    (table,) = sync(pipeline, graph)
    before = rows(pipeline, table)
    graph.errors[container_path] = (403, "40003")
    with pytest.raises(PipelineStepFailed):
        sync(pipeline, graph)
    assert rows(pipeline, table) == before


def test_long_retry_after_is_respected(monkeypatch):
    import cognee_community_connector_onenote.onenote as onenote

    delays = []
    monkeypatch.setattr(onenote.time, "sleep", delays.append)
    client = httpx.Client(
        transport=httpx.MockTransport(lambda _: httpx.Response(429, headers={"Retry-After": "301"}))
    )
    with client, pytest.raises(OneNoteError):
        list_notebooks("offline-token", http_client=client)
    assert delays == [301] * 4
